### ISSUE TITLE
How to delete Server?

### ISSUE THREAD

**Issue by anatoliykant** [ovh-ux/ovh-manager-cloud#1106]
### Description
I have two OVH Cloud servers. How can I remove one of them?
I created a ticket on the site ovh.com with this question.
4 days have passed since I asked the question, but no one answered me.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by FredericEspiau** [comment]
Hello @anatoliykant and thanks for your question !

Could you please show us a screenshot of your servers so we know what you are talking about ? You can hide sensible data if you want to.

**Comment by anatoliykant** [comment]
Hello, Frédéric Espiau.Here is a screenshot of what I was talking about. 15.10.2018, 13:29, "Frédéric Espiau" <notifications@github.com>:Hello @anatoliykant and thanks for your question !Could you please show us a screenshot of your servers so we know what you are talking about ? You can hide sensible data if you want to.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by FredericEspiau** [comment]
Wrong copy paste I think :)

**Comment by anatoliykant** [comment]
Here is a link to the screenshot - https://yadi.sk/i/RNXda2x0noAAiw15.10.2018, 12:37, "Frédéric Espiau" <notifications@github.com>:Wrong copy paste I think :)

**Comment by anatoliykant** [comment]
@FredericEspiau I updated link😐

**Comment by FredericEspiau** [comment]
@anatoliykant 

Here is what you should do:
* Click on your username in the top right corner of the screen
* A menu will appear. Click on **My services**
https://dl.plik.ovh/file/0a4eietWGt608adC/O13Q5asbeUtl1fVN/Capture%20d%E2%80%99e%CC%81cran%202018-10-15%20a%CC%80%2014.06.46.png
* You should see you products.
* Select the product you want to cancel and click on the menu at the end of the line.
* A menu should appear. Click on **Terminate on expiry date**.
https://dl.plik.ovh/file/0a4eietWGt608adC/FV35W82dkfwvTl4D/Capture%20d%E2%80%99e%CC%81cran%202018-10-15%20a%CC%80%2014.36.41.png
* You will be able to enjoy your service until it expires.

**Comment by anatoliykant** [comment]
@FredericEspiau The button **Terminate on expiry date** is inactive.
https://yadi.sk/i/yQ-xDX3l1OBYJQ
https://yadi.sk/i/3ded9yliRq1DJg

**Comment by FredericEspiau** [comment]
Then it will expire on 1 November without you having to do anything :)

**Comment by anatoliykant** [comment]
I would like to disable the server today.
