### ISSUE TITLE
Cannot list services in Vrack manager

### ISSUE THREAD

**Issue by miton18** [ovh-ux/ovh-manager-cloud#1235]
### Description

Since some weeks I can't add any project / dedicated servers to my VRack.

### Steps to Reproduce

1. Go to your VRack manager [https://www.ovh.com/manager/cloud/index.html#/vrack/pn-xxxxx](https://www.ovh.com/manager/cloud/index.html#/vrack/pn-xxxxx)
2. Wait for your service list
3. nothing happens

**Expected behavior:**

The complete list of my services.

**Actual behavior:**

Nothing, no error message, but a 504 in the manager console, with the message:
`504 Gateway Time-out`

**Reproduces how often:**
Every time I load this VRack

### Additional Information
The call which failed with a 504 is:
https://www.ovh.com/engine/2api/vrack/pn-xxxxx/allowedServices

**Comment by FredericEspiau** [comment]
Thanks for your input ! A JIRA has been created: MANAGER-2032

I'll come back to you this week

**Comment by FredericEspiau** [comment]
This is fixed for you @miton18  ?

**Comment by miton18** [comment]
Yes ! thx !

**Comment by FredericEspiau** [comment]
Good to know :)
