### ISSUE TITLE
LICENSE not detected by github

### ISSUE THREAD

**Issue by bnjjj** [ovh-ux/ovh-manager-cloud#31]
The license type isn't detected by Github like on https://github.com/ovh-ux/ovh-manager-telecom repository. Maybe missing a setting

**Comment by BaptisteDixneuf** [comment]
Probably remove the empty line in the LICENSE file
https://github.com/ovh-ux/ovh-manager-cloud/blob/e574067454334ed0152788312bd89c0b3aa9c1c4/LICENSE#L1

**Comment by Netnix** [comment]
I removed the empty line, it did not work.
I removed the file and replaced it starting with a template from Github, it did not work.

:(
