### ISSUE TITLE
oui-loader used in index.tpl.html

### ISSUE THREAD

**Issue by Jisay** [ovh-ux/ovh-manager-cloud#472]
Old `oui-loader` directive is still used in loading part in index.tpl.html :

https://github.com/ovh-ux/ovh-manager-cloud/blob/91c6055bdfb123cefc5ab5a7a428b82861dd9e47/client/index.tpl.html#L65

`oui-spinner` directive should be used instead. Even better, the `.oui-spinner` classes could be used to avoid delay due to angular bootstrap process.

**Comment by AxelPeter** [comment]
Not only index.tpl.html: https://github.com/ovh-ux/ovh-manager-cloud/pull/473/files

**Comment by Netnix** [comment]
Fixed with https://github.com/ovh-ux/ovh-manager-cloud/pull/473
